pool:
  vmImage: "windows-latest"

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - pipeline-marsrover.yml
    - ../src

variables:
  buildConfiguration: 'release'

steps:
- task: UseDotNet@2
  displayName: 'Install NET6'
  inputs:
    version: 6.x

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    projects: '../src/MarsRover.Pilot.API.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish solution'
  inputs:
    command: publish
    projects: '../src/MarsRover.Pilot.API.sln'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)"'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'